spring:
  application:
    name: cube-ms-eureka
server:
  port: ${PORT:8761}
eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
       defaultZone: ${EUREKA_DEFAULT_ZONE}
  server:
    enableSelfPreservation=false:
